package com.guzman.unx.eod.details.valueobjects;

public enum InstinetValuePosition {
	CLIENT_NAME, CLIENT_NETWORK, EMS_ORDER_ID, CLORDID, ORIGCLORDID, EMSCLORID, ORIG_EMS_CLORDID,//7
	TRADEDATE, LISTID, SYMBOL, ID_SOURCE, SECURITY_ID, SIDE, PRIMARY_EXCHANGE, CLIENT_SHARES, CLIENT_ORDER_TYPE,//16
	CLIENT_LMT_PX, CLIENT_TIF, DESTINATION, EXEC_BROKER, MPID, ALGO_STRATEGY, ALGO_PARAMETERS, WAVE_ID,//24
	WAVE_SHARES, WAVE_ORDER_TYPE, WAVE_LMT_PX, WAVE_TIF, EXEC_ID, LASTSH, LASTPX, DATETIME_ORDER_RECEIVED, //32
	DATETIME_ROUTED, DATETIME_EXECUTED //34
}
