package com.guzman.unx.eod.details.valueobjects;

public enum ITGValuesPositions {
	
EMS_NAME,EMS_ORDER_ID,GUZCLORDID,ORIGGUZCLORDID,EMSCLORDID,ORIGEMSCLORDID, //5
TRADEDATE,LISTID,SYMBOL,IDSOURCE,SECURITYID,//10
SIDE,ORDERSHARES,ORDERTYPE,PXCLIENTLMT,PRIMARYEXCHANGE,//15
TIF,DESTINATION,EXECUTINGBROKER,MPID,ALGOSTRATEGY,//20
ALGOPARAMETERS,WAVEID,WAVESHARES,WAVEORDERTYPE,WAVELMTPX,//25
WAVETIF,EXECID,EXECREFID,LASTSH,LASTPX,//30
DATETIME_ORDERRECEIVED,DATETIME_ROUTED,DATETIME_EXECUTED;//33

}
